lang: fr
title: DevFusion
email: martin.gilbert@dev-fusion.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogue d’un développeur fusion, réflexions, découvertes et tutoriels…
  Les différentes technos sont à la programmation ce que le funk, le blues et le rock sont au jazz fusion. Un moyen pour répondre à un besoin, il faut parfois les mixer pour donner la meilleure réponse.
baseurl: ""
url: "https://dev-fusion.com"
twitter_username: null
github_username: official-dev-fusion

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
